mqtt_broker_addr = "172.31.65.64"
mqtt_broker_port = 1883
mqtt_client_id = "keypad-util"
mqtt_subscribe_prefix = "mx-blue"

[initial_state_released]
row_0 = [
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
]

row_1 = [
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
]

row_2 = [
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
]

row_3 = [
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
]

row_4 = [
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
    [0, 50, 0],
]

[initial_state_pressed]
row_0 = [
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
]

row_1 = [
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
]

row_2 = [
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
]

row_3 = [
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
]

row_4 = [
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
    [50, 0, 0],
]
